![Cutie Hare](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg/1452px-SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg?20170313021652)


This file is made available under the Creative Commons CC0 1.0 Universal Public Domain Dedication.
The person who associated a work with this deed has dedicated the work to the public domain by waiving all of their rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law. You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission.

In [13]:
import pandas as pd
import numpy as np

In [12]:
URL = "https://pasta.lternet.edu/package/data/eml/knb-lter-bnz/55/22/f01f5d71be949b8c700b6ecd1c42c701"
hares = pd.read_csv(URL)

In [48]:
hares.dtypes

date           object
time           object
grid           object
trap           object
l_ear          object
r_ear          object
sex            object
age            object
weight        float64
hindft        float64
notes          object
b_key         float64
session_id    float64
study          object
dtype: object

In [35]:
hares.head()
hares.shape
hares.isnull().sum()
hares['weight'].max() # 2365 
hares['weight'].min() # 0 
hares['hindft'].max() # 160
hares['hindft'].min() #60

60.0

In [45]:
# change the place where weight = 0 to an NA 
hares[hares['weight'] == 0] = np.nan

date            8/2/2000
time                 NaN
grid              bonrip
trap                  4C
l_ear                784
r_ear                785
sex                    F
age                    J
weight             830.0
hindft             145.0
notes                NaN
b_key              673.0
session_id          57.0
study         Population
Name: 375, dtype: object

In [47]:
hares['age'].unique()

array([nan, 'J', 'A', 'a 1 yr.', 'a 3/4 yr.', 'a 1 yr', '1 yr', '1 yr.',
       '2 yrs.', '2 yrs', 'a 2 yrs.', '2.25 yrs', '3.5 yrs.', '3 yrs.',
       '2.5 yrs', '3.25 yrs.', 'A 1.5', '?', 'U', 'j', 'a', 'u', 'J 3/4',
       'A 3/4', 'A 1/2', '3/4/2013', '1/4/2013', '1/2/2013', '1', '1.25',
       '1.5'], dtype=object)

In [49]:
hares['sex'].unique()

array([nan, 'M', 'F', '?', 'F?', 'M?', 'pf', 'm', 'f', 'f?', 'm?', 'f ',
       'm '], dtype=object)

### Exploratory Question 
Why is the age and sex columns so messed up? 

## Detecting messy values

### Table for allows sex values 

| Syntax      | Description   |
| ----------- | ------------- |
| m           | male          |
| f           | female        |
| m?          | Not confirmed |

In [62]:
hares['sex'].value_counts().unique

<bound method Series.unique of sex
F     1161
M      730
f      556
m      515
?       40
F?      10
f        4
m        4
f?       3
M?       2
m?       2
pf       1
Name: count, dtype: int64>

In [65]:
hares['sex'].value_counts(dropna = False).unique

<bound method Series.unique of sex
F      1161
M       730
f       556
m       515
NaN     352
?        40
F?       10
f         4
m         4
f?        3
M?        2
m?        2
pf        1
Name: count, dtype: int64>

### Discuss 
This column sucks. Citizian science = dif people recording data. People need a standarized way of discovering and inputing data. 

### e 
Theres whitespace! Need to strip

In [89]:
hares['sex'] = hares['sex'].str.strip()
hares['sex'] = hares['sex'].str.lower()
hares[(hares['sex'] == "?") | (hares['sex'] == "pd") | (hares['sex'] == "f?") ] = np.nan


In [90]:
hares['sex'].unique()


array([nan, 'm', 'f', 'm?'], dtype=object)